"""add user numbers"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f492acfe5f7'
down_revision: Union[str, None] = '235477082496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_numbers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('msisdn', sa.String(length=20), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_numbers_user_id'), 'user_numbers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_numbers_user_id'), table_name='user_numbers')
    op.drop_table('user_numbers')
    # ### end Alembic commands ###
