"""add reseller orders"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b2321be5d85'
down_revision: Union[str, None] = '9c5c62dddfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('order_reference', sa.String(length=100), nullable=False),
    sa.Column('bundle_code', sa.String(length=100), nullable=False),
    sa.Column('monty_order_id', sa.String(length=100), nullable=True),
    sa.Column('iccid', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='order_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iccid'),
    sa.UniqueConstraint('monty_order_id')
    )
    op.create_index(op.f('ix_orders_order_reference'), 'orders', ['order_reference'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_reference'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
