"""add local catalog"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c5c62dddfd3'
down_revision: Union[str, None] = '1f492acfe5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbr', sa.String(length=20), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('popular', sa.Boolean(), nullable=False),
    sa.Column('tagline_ru', sa.Text(), nullable=False),
    sa.Column('tagline_tj', sa.Text(), nullable=False),
    sa.Column('tagline_en', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr')
    )
    op.create_table('premium_numbers',
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('msisdn', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.Enum('PLATINUM', 'GOLD', 'SILVER', 'STANDARD', name='premium_number_tier'), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msisdn')
    )
    op.create_index(op.f('ix_premium_numbers_operator_id'), 'premium_numbers', ['operator_id'], unique=False)
    op.create_table('tariffs',
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(length=50), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('sms', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('best', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_operator_id'), 'tariffs', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariffs_operator_id'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_premium_numbers_operator_id'), table_name='premium_numbers')
    op.drop_table('premium_numbers')
    op.drop_table('operators')
    # ### end Alembic commands ###
