"""harden OTP attempts"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9dc73156e1ee'
down_revision: Union[str, None] = '0517b2dce52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_requests', sa.Column('failed_attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_requests', 'failed_attempts')
    # ### end Alembic commands ###
